---
- hosts: localhost
  connection: local
  tasks:
  - name: Remove any existing create-keytabs.ps1
    shell: ssh Administrator@{{ ad_hostname }} del C:\\Users\\Administrator\\create-keytabs.ps1

  - name: Remove any existing keytabs
    shell: ssh Administrator@{{ ad_hostname }} del C:\\Users\\Administrator\\*.keytab

  - name: SCP the create-keytabs.ps1 to the Active Directory server
    shell: scp ../output/keytabs/create-keytabs.ps1 Administrator@{{ ad_hostname }}:/C:\\Users\\Administrator

  - name: Run the create-keytabs.ps1 to add credentials
    shell: ssh Administrator@{{ ad_hostname }} powershell C:\\Users\\Administrator\\create-keytabs.ps1

  - name: SCP the keytabs back to localhost
    shell: scp Administrator@{{ ad_hostname }}:/C:\\Users\\Administrator\\{{ kafka_cluster_identifier }}-{{ item }}.keytab ../output/keytabs/
    with_items: 
      - "{{ beta_packages }}"
      - clients
  