---
- hosts: localhost
  connection: local
  tasks:
  - name: Base64 encode Kafka Broker keytab
    shell: cat ../output/keytabs/{{ kafka_cluster_identifier }}-brokers.keytab | base64 | tr -d '\n' > ../output/keytabs/{{ kafka_cluster_identifier }}-brokers.keytab.base64
    when: all_the_security == true

  - name: Add Kakfa Broker keytab as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/__dcos_base64__brokers_keytab -f ../output/keytabs/{{ kafka_cluster_identifier }}-brokers.keytab.base64
    when: all_the_security == true

  - name: Base64 encode Zookeeper keytab
    shell: cat ../output/keytabs/{{ kafka_cluster_identifier }}-zookeeper.keytab | base64 | tr -d '\n' > ../output/keytabs/{{ kafka_cluster_identifier }}-zookeeper.keytab.base64
    when: all_the_security == true

  - name: Add Zookeeper keytab as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/__dcos_base64__zookeeper_keytab -f ../output/keytabs/{{ kafka_cluster_identifier }}-zookeeper.keytab.base64
    when: all_the_security == true

  - name: Base64 encode Kafka Client keytab
    shell: cat ../output/keytabs/{{ kafka_cluster_identifier }}-clients.keytab | base64 | tr -d '\n' > ../output/keytabs/{{ kafka_cluster_identifier }}-clients.keytab.base64
    when: all_the_security == true

  - name: Add Kafka Client keytab as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/__dcos_base64__clients_keytab -f ../output/keytabs/{{ kafka_cluster_identifier }}-clients.keytab.base64
    when: all_the_security == true

  - name: Base64 encode Schema keytab
    shell: cat ../output/keytabs/{{ kafka_cluster_identifier }}-schema.keytab | base64 | tr -d '\n' > ../output/keytabs/{{ kafka_cluster_identifier }}-schema.keytab.base64
    when: all_the_security == true

  - name: Add Schema keytab as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/__dcos_base64__schema_keytab -f ../output/keytabs/{{ kafka_cluster_identifier }}-schema.keytab.base64
    when: all_the_security == true

  - name: Add krb5.conf as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/krb5 -f ../output/other/{{ kafka_cluster_identifier }}-krb5.conf
    when: all_the_security == true

  - name: Add client-jaas.conf as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/jaas -f ../output/other/{{ kafka_cluster_identifier }}-client-jaas.conf
    when: all_the_security == true