---
- hosts: localhost
  connection: local
  tasks:
  - name: Base64 encode Kafka keytabs
    shell: cat ../output/keytabs/{{ kafka_cluster_identifier }}-{{ item }}.keytab | base64 | tr -d '\n' > ../output/keytabs/{{ kafka_cluster_identifier }}-{{ item }}.keytab.base64
    with_items: "{{ beta_packages }}"
    when: all_the_security == true

  - name: Add keytabs as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/__dcos_base64__{{ item  }}_keytab -f ../output/keytabs/{{ kafka_cluster_identifier }}-{{ item }}.keytab.base64
    with_items: "{{ beta_packages }}"
    when: all_the_security == true

  - name: Add client-jaas.conf as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/{{ item }}-jaas -f ../output/other/{{ kafka_cluster_identifier }}-{{ item }}-client-jaas.conf
    with_items: "{{ community_packages }}"
    when: all_the_security == true

  - name: Add krb5.conf as a secret
    command: dcos security secrets create {{ service_group }}/{{ kafka_cluster_identifier }}-kafka/krb5 -f ../output/other/{{ kafka_cluster_identifier }}-krb5.conf
    when: all_the_security == true
