---
- hosts: localhost
  connection: local
  tasks:
  - name: Base64 encode Kafka Broker keytab
    shell: cat ../output/{{ kafka_cluster_identifier }}-brokers.keytab | base64 | tr -d '\n' > ../output/{{ kafka_cluster_identifier }}-brokers.keytab.base64
    when: all_the_security == true

  - name: Add Kakfa Broker keytab as a secret
    command: dcos security secrets create __dcos_base64__{{ kafka_cluster_identifier }}_brokers_keytab -f ../output/{{ kafka_cluster_identifier }}-brokers.keytab.base64
    when: all_the_security == true

  - name: Base64 encode Zookeeper keytab
    shell: cat ../output/{{ kafka_cluster_identifier }}-zookeeper.keytab | base64 | tr -d '\n' > ../output/{{ kafka_cluster_identifier }}-zookeeper.keytab.base64
    when: all_the_security == true

  - name: Add Zookeeper keytab as a secret
    command: dcos security secrets create __dcos_base64__{{ kafka_cluster_identifier }}_zookeeper_keytab -f ../output/{{ kafka_cluster_identifier }}-zookeeper.keytab.base64
    when: all_the_security == true

  - name: Base64 encode Kafka Client keytab
    shell: cat ../output/{{ kafka_cluster_identifier }}-clients.keytab | base64 | tr -d '\n' > ../output/{{ kafka_cluster_identifier }}-clients.keytab.base64
    when: all_the_security == true

  - name: Add Kafka Client keytab as a secret
    command: dcos security secrets create __dcos_base64__{{ kafka_cluster_identifier }}_clients_keytab -f ../output/{{ kafka_cluster_identifier }}-clients.keytab.base64
    when: all_the_security == true

  - name: Base64 encode Schema keytab
    shell: cat ../output/{{ kafka_cluster_identifier }}-schema.keytab | base64 | tr -d '\n' > ../output/{{ kafka_cluster_identifier }}-schema.keytab.base64
    when: all_the_security == true

  - name: Add Schema keytab as a secret
    command: dcos security secrets create __dcos_base64__{{ kafka_cluster_identifier }}_schema_keytab -f ../output/{{ kafka_cluster_identifier }}-schema.keytab.base64
    when: all_the_security == true

  - name: Add krb5.conf as a secret
    command: dcos security secrets create {{ kafka_cluster_identifier }}_krb5 -f ../output/{{ kafka_cluster_identifier }}-krb5.conf
    when: all_the_security == true

  - name: Add client-jaas.conf as a secret
    command: dcos security secrets create {{ kafka_cluster_identifier }}_jaas -f ../output/{{ kafka_cluster_identifier }}-client-jaas.conf
    when: all_the_security == true