---
- hosts: localhost
  connection: local
  tasks:
  - name: Check dcos-enterprise-cli is installed
    command: dcos security org users grant
    register: grant_check
    ignore_errors: True

  - name: Install dcos-enterprise-cli if not available
    command: dcos package install dcos-enterprise-cli --cli --yes
    when: grant_check.stderr.find('No such command') != -1

  - name: Check if dcos-enterprise-cli installed correctly or fail
    command: dcos security org users grant
    register: grant_check_installed
    failed_when: grant_check_installed.stderr.find('No such command') != -1