---
- hosts: localhost
  connection: local
  tasks:
  - name: Delete full stack
    shell: dcos package uninstall {{ item }} --app-id={{ service_group }}/{{ kafka_cluster_identifier }}-kafka/{{ kafka_cluster_identifier }}-{{ item }} --yes
    with_items: "{{ beta_packages }}"
    ignore_errors: true

  - name: Delete keytab secrets
    shell: dcos security secrets delete /{{ service_group }}/{{ kafka_cluster_identifier }}-kafka/__dcos_base64__{{ item }}_keytab
    with_items: "{{ beta_packages }}"
    ignore_errors: true

  - name: Delete keystore secret
    shell: dcos security secrets delete /{{ service_group }}/{{ kafka_cluster_identifier }}-kafka/__dcos_base64__mykeystore
    ignore_errors: true

  - name: Delete client-jaas.conf secrets
    shell: dcos security secrets delete /{{ service_group }}/{{ kafka_cluster_identifier }}-kafka/{{ item }}-jaas
    with_items: "{{ community_packages }}"
    ignore_errors: true

  - name: Delete krb5.conf secret
    shell: dcos security secrets delete /{{ service_group }}/{{ kafka_cluster_identifier }}-kafka/krb5
    ignore_errors: true

  - name: Delete service accounts
    shell: dcos security org service-accounts delete {{ kafka_cluster_identifier }}-{{ beta_or_ga }}-{{ item }}
    with_items:
      - kafka-zookeeper
      - kafka
    ignore_errors: true

  - name: Delete service account key secrets
    shell: dcos security secrets delete /{{ service_group }}/{{ kafka_cluster_identifier }}-kafka/{{ beta_or_ga }}-{{ item }}-private-key
    with_items:
      - kafka-zookeeper
      - kafka
    ignore_errors: true


