---
- hosts: localhost
  connection: local
  tasks:
  - set_fact: package="{{ package_to_install }}"

  - import_tasks: security.yaml
    when: package == "confluent-zookeeper" or package == "beta-confluent-zookeeper" or package == "confluent-kafka" or package == "beta-confluent-kafka"

  - name: Install {{ kafka_cluster_identifier}}-{{ package }}
    command: dcos package install {{ package }} --options=../output/options/{{ kafka_cluster_identifier}}-{{ package }}.json --yes