---
- hosts: localhost
  connection: local
  tasks:
  - name: Install dcos enterprise cli subcommand
    command: dcos package install dcos-enterprise-cli --cli --yes

  - name: Install confluent kafka cli subcommand
    command: dcos package install confluent-kafka --cli --yes

  - name: Install confluent zookeeper cli subcommand
    command: dcos package install confluent-zookeeper --cli --yes