---
- hosts: localhost
  connection: local
  tasks:
  - name: Build the client-jaas.conf in the output directory
    template: src=../templates/client-jaas/{{ item }}-client-jaas.conf.j2 dest=../output/other/{{ kafka_cluster_identifier }}-{{ item }}-client-jaas.conf
    with_items: "{{ community_packages }}"


  - name: Build the krb5.conf in the output directory
    template: src=../templates/other/krb5.conf.j2 dest=../output/other/{{ kafka_cluster_identifier }}-krb5.conf

  - name: Build the client.properties in the output directory
    template: src=../templates/other/client.properties.j2 dest=../output/other/{{ kafka_cluster_identifier }}-client.properties