---
- hosts: localhost
  connection: local
  tasks:
  - name: Build the create_keytabs batch script in the output directory
    template: src=../templates/create_keytabs.bat.j2 dest=../output/create-keytabs.bat