---
- hosts: localhost
  connection: local
  tasks:
  - name: Build the client-jaas-testing.conf in the output directory
    template: src=../templates/other/schema-registry-testing.sh.j2 dest=../output/other/{{ kafka_cluster_identifier }}-schema-registry-testing.sh